[project]
name = "Rivora-backend"
version = "0.1.0"
description = "Backend of multi e vendor e commerce application"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.129.0",
]
